# Generated by Django 4.1.1 on 2022-12-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='cruise_line',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cruise_liner_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='general_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='length_in_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='ship_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='review',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.DeleteModel(
            name='CruiseLine',
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
