# Generated by Django 4.1.2 on 2022-12-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_ship_cruise_line_remove_trip_ship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cruise_liner_name',
            field=models.CharField(choices=[('Carnival', 'Carnival'), ('Celestyal', 'Celestyal'), ('Costa', 'Costa'), ('Disney', 'Disney'), ('MSC', 'MSC'), ('Norwegian', 'Norwegian'), ('Princess', 'Princess'), ('Royal Carribean International', 'Royal Carribean International'), ('Virgin Voyages', 'Virgin Voyages'), ('Azamara', 'Azamara'), ('Celebrity', 'Celebrity'), ('Holland America', 'Holland America'), ('Oceania', 'Oceania'), ('Viking', 'Viking'), ('Cunard', 'Cunard'), ('Regent Seven Seas', 'Regent Seven Seas'), ('Seabourn', 'Seabourn'), ('Sea Dream', 'Sea Dream'), ('Silversea', 'Silversea'), ('Swan Hellenic', 'Swan Hellenic'), ('Windstar', 'Windstar')], default='Carnival', max_length=30, verbose_name='Cruise Line'),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_location',
            field=models.CharField(max_length=30, null=True, verbose_name='General Location'),
        ),
        migrations.AlterField(
            model_name='review',
            name='length_in_days',
            field=models.IntegerField(null=True, verbose_name='Length of Trip (in days)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='', max_length=30, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ship_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Ship Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)], default=3, verbose_name='Star Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date (YYYY-MM-DD)'),
        ),
    ]
