# Generated by Django 4.1.2 on 2022-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_review_comments_alter_review_cruise_liner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='start_date',
        ),
        migrations.AddField(
            model_name='review',
            name='month',
            field=models.CharField(choices=[(4, 4), (8, 8), (5, 5), (7, 7), (9, 9), (1, 1), (10, 10), (3, 3), (12, 12), (2, 2), (6, 6), (11, 11)], max_length=10, null=True, verbose_name='Month'),
        ),
    ]
