# Generated by Django 4.1.2 on 2022-12-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_review_start_date_review_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='month',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=10, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (5, 5), (4, 4)], default=3, verbose_name='Star Rating'),
        ),
    ]
